org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1


# Mod
mod_id=runic_curiosities
mod_name=Runic Curiosities [Magic & Items]
mod_license=MIT and HydroVoltz (SavistarIT)
mod_version=1.20.1-1.2.3
mod_group_id=com.runiccuriosities_pck
mod_authors=HydroVoltz (SavistarIT)
mod_description=A unique and elegant talisman mod that adds 2D runic trinkets and other things compatible with Curios API and Geckolib.
mod_logo_file=icon.png