modLoader="javafml"
loaderVersion="[47,)"
license="MIT and HydroVoltz (SavistarIT)"

[[mods]]
modId="runic_curiosities"
version="1.1.0-beta"
displayName="Runic Curiosities [Magic & Items]"
authors="HydroVoltz (SavistarIT)"
logoFile="icon.png"
description='''
A unique and elegant talisman mod that adds 2D runic trinkets and other things compatible with Curios API and Geckolib.
'''

[[dependencies.runic_curiosities]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.runic_curiosities]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"