modLoader="javafml"
loaderVersion="[47,)"
license="MIT and HydroVoltz (SavistarIT)"

[[mods]]
modId="runic_curiosities"
version="1.1.0"
displayName="Runic Curiosities"
authors="HydroVoltz (SavistarIT)"
logoFile="icon.png"
description='''
A simple and elegant talisman mod that adds 2D runic trinkets compatible with Curios API.
'''

[[dependencies.runic_curiosities]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.runic_curiosities]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"